### ISSUE TITLE
complex if statements

### ISSUE THREAD

**Issue by noor-sawaed** [WebAhead10/week3-project-hseen-abed-adan#2]
no usage of if else line 18 +13
https://github.com/WebAhead10/week3-project-hseen-abed-adan/blob/main/script.js#L13
https://github.com/WebAhead10/week3-project-hseen-abed-adan/blob/main/script.js#L18
its a bit complicated to understand to the naked eye should be a little explained.

**Comment by Adan-Sa** [comment]
We will add comments to make it more clear, but using ternary operator is faster, simplier & it takes less space.
